changed line 160 from df.append to pd.concat()
Pandas recently updated to v2.0+ and depreciated df.append() functionality.

File "C:\Users\Tim\Programs\Ataraxia\src\character-gen.py", line 169, in <module>
    main()
  File "C:\Users\Tim\Programs\Ataraxia\src\character-gen.py", line 160, in main
    lpdf = lpdf.append(selected_row, ignore_index=True)
            ^^^^^^^^^^^^
  File "C:\Users\Tim\anaconda3\Lib\site-packages\pandas\core\generic.py", line 6204, in __getattr
    return object.getattribute(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'append'. Did you mean: '_append'?

(base) C:\Users\Tim\Programs\Ataraxia\src>